version: "3.9"

services:
  postgres:
    image: supabase/postgres:17.6.1.022
    container_name: pg_proto
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c listen_addresses='*'
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=10
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 2s
      retries: 10

  walstream:
    build: ./stream
    container_name: walstream
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: pass
      PGDATABASE: postgres
      PGPORT: 5432
    ports:
      - "9000:9000"
    networks:
      - default

volumes:
  pgdata:
